apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: atomist
    app.kubernetes.io/name: sdm
    app.kubernetes.io/part-of: sdm
  name: sdm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: atomist
    app.kubernetes.io/name: k8s-sdm
    app.kubernetes.io/part-of: k8s-sdm
    atomist.com/workspaceId: T29E48P34
  name: k8s-sdm
  namespace: sdm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: atomist
    app.kubernetes.io/name: k8s-sdm
    app.kubernetes.io/part-of: k8s-sdm
    atomist.com/workspaceId: T29E48P34
  name: k8s-sdm
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods", "secrets", "serviceaccounts", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "clusterrolebindings", "roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: atomist
    app.kubernetes.io/name: k8s-sdm
    app.kubernetes.io/part-of: k8s-sdm
    atomist.com/workspaceId: T29E48P34
  name: k8s-sdm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-sdm
subjects:
  - kind: ServiceAccount
    name: k8s-sdm
    namespace: sdm
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app.kubernetes.io/managed-by: atomist
    app.kubernetes.io/name: k8s-sdm
    app.kubernetes.io/part-of: k8s-sdm
    atomist.com/workspaceId: T29E48P34
  name: k8s-sdm
  namespace: sdm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-sdm
      atomist.com/workspaceId: T29E48P34
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: atomist
        app.kubernetes.io/name: k8s-sdm
        app.kubernetes.io/part-of: k8s-sdm
        app.kubernetes.io/version: "1"
        atomist.com/workspaceId: T29E48P34
    spec:
      containers:
        - env:
            - name: ATOMIST_CONFIG_PATH
              value: /opt/atm/client.config.json
            - name: TMPDIR
              value: /tmp
          image: atomist/k8s-sdm:1.1.1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 3
          name: k8s-sdm
          ports:
            - name: http
              containerPort: 2866
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 500m
              memory: 384Mi
            requests:
              cpu: 100m
              memory: 320Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /opt/atm
              name: k8s-sdm
              readOnly: true
            - mountPath: /home/atomist
              name: home
            - mountPath: /tmp
              name: tmp
      initContainers:
        - args:
            - git config --global user.email 'bot@atomist.com' && git config --global user.name 'Atomist Bot'
          command: ["/bin/sh", "-c"]
          image: atomist/sdm-base:0.2.0
          name: "home"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /home/atomist
              name: home
      securityContext:
        fsGroup: 2866
        runAsGroup: 2866
        runAsNonRoot: true
        runAsUser: 2866
        supplementalGroups: []
        sysctls: []
      serviceAccountName: k8s-sdm
      volumes:
        - name: k8s-sdm
          secret:
            defaultMode: 288
            secretName: k8s-sdm
        - emptyDir: {}
          name: home
        - emptyDir: {}
          name: tmp
